### PR TITLE
[FEATURE] materialized views

### LINKED ISSUE #870: [Feature] Add Materialized View as a Materialization to dbt-snowflake
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt-snowflake functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Snowflake has an object type called [Materialized Views](https://docs.snowflake.com/en/sql-reference/sql/create-materialized-view). I'm aware that dbt-snowflake previously supported these and it was archived into the [dbt-labs-experimental-features repo](https://github.com/dbt-labs/dbt-labs-experimental-features/tree/main/materialized-views]=), I'm unsure as to why this logic was deprecated.

The Dbt Docs currently suggest using dynamic tables instead of materialized views in Snowflake, but having recently had a call with a Senior Snowflake Solutions Architect it was made apparent that dynamic tables aren't a replacement for materialized views and in fact, they are often used in combination (i.e. a materialized view may sit on top of a dynamic table). I have considered manually creating a materialised view outside of dbt however it would be much preferable to contain all of the DDL within the dbt project.

### Describe alternatives you've considered

I've considered the following alternatives
- Manually maintaining a materialised view outside of dbt
- Creating a custom materialization, though this seems to be infeasible given that `Materialized View` isn't a RelationType defined in  [relation.py](https://github.com/dbt-labs/dbt-snowflake/blob/0374b4ec948982f2ac8ec0c95d53d672ad19e09c/dbt/adapters/snowflake/relation.py)

### Who will this benefit?

All Snowflake Users should find a benefit in having access to Materialized Views, it is often recommended as a performance improvement by Snwoflake Support

### Are you interested in contributing this feature?

Happy to contribute though am not familiar with the dbt codebase

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by jeremy-thomas-roc**
resolves #870
[docs](https://github.com/dbt-labs/docs.getdbt.com/issues/new/choose) dbt-labs/docs.getdbt.com/#

### Problem

materialized views are currently not support for Snowflake. rather, dynamic tables were implemented, to be more consistent with other provider's concept of materialized views. however, there are still valid use cases for MVs, and so I figured it take a shot at implementing them.

### Solution

this is my first attempt at contributing to dbt, so forgive me if this is not a great solution. i essentially reused the logic for views, with some minor changes to support the materialized version. i also added a check to the `SnowflakeRelation` object to see if a relation was an MV, for support within the macros.

### Checklist

- [X] I have read [the contributing guide](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md) and understand what's expected of me
- [X] I have run this code in development and it appears to resolve the stated issue
- [x] This PR includes tests, or tests are not required/relevant for this PR
- [ ] This PR has no interface changes (e.g. macros, cli, logs, json artifacts, config files, adapter interface, etc) or this PR has already received feedback and approval from Product or DX

### CODE REVIEW

**Comment by jeremy-thomas-roc** [comment]
as a note, i have not implemented testing, as left this in draft to make sure i am headed the right direction before diving into testing

**Comment by cp-rohitdesai** [comment]
@dbt-labs/adapters  team,
May we know when this PR will get merged and make this materialized view option available with dbt deployment in snowflake? Any estimated timeline or info on dbt version in which this will available will be helpful. 
Though, I see some of githubs checks are still in queue.

**Comment by jeremy-thomas-roc** [comment]
@mikealfare or any other maintainers: I would appreciate some initial review on this, even if it is not ready to go in its current state. I believe there is more testing, more edge cases, and other handling that could be implemented here, but without some feedback on the current state, I'm not sure how to proceed.

**Comment by BenoitLF** [comment]
Commenting as well to say that we would love to have this PR merged.
Who should we ask to have visibility ?

**Comment by BenoitLF** [comment]
@mikealfare maybe ?

**Comment by jeremy-thomas-roc** [comment]
@mikealfare Can we get some indication of the priority of this at least? I understand that it is a large implementation step, but radio silence from maintainers is frustrating. I'm happy to put in more time working on this, our current workaround is  sub-optimal at best and I'd be happy to contribute to help others as well.

**Comment by amychen1776** [comment]
Hi folks! I'm Amy - I'm the Product Manager for the Adapters team. 
First, I want to say that I very much appreciate the work that @jeremy-thomas-roc  have done here. Community contributions and discussions are always meaningful, and that's part of what makes great open-source software. 

In terms of tagging and communication - I'm the one responsible for triaging and defining scope. Feel free to tag me or just simply chat with me in dbt Slack (I monitor it at least once a week). :) No need to tag our engineers for things like this (especially since they are not responsible for assigning work). 

This PR is super helpful in helping us scope out and get a head start for supporting MVs in dbt-snowflake. Unfortunately, MVs for Snowflake are not on our roadmap for the next quarter and thus, we are not able to merge in the PR and thus establishing dbt support/maintainership for MV support. I will be reviewing this next quarter and will be happy to make updates if things change on the associated issue.

**Comment by jeremy-thomas-roc** [comment]
@amychen1776 

> Hi folks! I'm Amy - I'm the Product Manager for the Adapters team. First, I want to say that I very much appreciate the work that @jeremy-thomas-roc have done here. Community contributions and discussions are always meaningful, and that's part of what makes great open-source software.
> 
> In terms of tagging and communication - I'm the one responsible for triaging and defining scope. Feel free to tag me or just simply chat with me in dbt Slack (I monitor it at least once a week). :) No need to tag our engineers for things like this (especially since they are not responsible for assigning work). Please also note that I am one person, and we have multiple repositories to oversee.
> 
> That said, this PR is super helpful in helping us scope out and get a head start for supporting MVs in dbt-snowflake. Unfortunately, MVs for Snowflake are not on our roadmap for the next quarter and thus, we are not able to merge in the PR and thus establishing continous dbt support/maintainership for MVs. I will revisit this next quarter and will be happy to update if things change on the associated issue.

Thank you for providing some insight. Apologies for tagging Mike, he seemed like the most active person in the repo and the most likely to provide an answer. 

Obviously, there isn't much we can do but hope it appears on the roadmap, but hopefully the fact that there are multiple people asking about this feature can help push it in the right direction.

I'm closing this PR based on your comment, and can reopen if it is on the horizon.

**Comment by amychen1776** [comment]
No worries! I totally understand - it's not always very clear who to tag (which I feel like we can figure out improvements there). And to emphasize again, we truly appreciate the work you did here!

**Pull request closed without merging**
