### PR TITLE
Bump SCP upper bound to <2.9

### PR DESCRIPTION
**Pull request by jtcohen6**
- We should make a habit of bumping these important dependencies in `dbt-core` minor versions
- I'm not sure why `dependabot` isn't opening these PRs for us (https://github.com/dbt-labs/dbt-snowflake/issues/28)

### CODE REVIEW

**Review by dbeatty10 — APPROVED** [review]
👍 Confirmed that `snowflake-connector-python` version `2.8.0` got covered in one of the test suites that passed in CI, which confirms that this change actually got tested as intended:
```
  Using cached snowflake_connector_python-2.8.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (21.3 MB)
```

**Comment by dbeatty10** [comment]
@jlopezpena thank you for checking in.

This is blocked on https://github.com/dbt-labs/dbt-snowflake/pull/307 right now. We should be able to merge this after that is resolved.

**Comment by dbeatty10** [comment]
@jtcohen6 I went ahead and merged this in. Please let me know if I overstepped.

**Comment by jtcohen6** [comment]
@dbeatty10 thanks for doing it!!

**Pull request merged**
