### PR TITLE
Fix Issue URLs in Changelog

### PR DESCRIPTION
**Pull request by kevin868**
### Description
Links were directing to dbt-spark, instead of -snowflake..

- [ ] did NOT ~run `changie new`.. is this necessary for *editing* an old entry?~

### Checklist

- [X] I have read [the contributing guide](https://github.com/dbt-labs/dbt-snowflake/blob/main/CONTRIBUTING.md) and understand what's expected of me
- [X] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
- [X] I have run this code in development and it appears to resolve the stated issue
- [X] This PR includes tests, or tests are not required/relevant for this PR
- [X] I have [opened an issue to add/update docs](https://github.com/dbt-labs/docs.getdbt.com/issues/new/choose), or docs changes are not required/relevant for this PR
- [x] I have run `changie new` to [create a changelog entry](https://github.com/dbt-labs/dbt-snowflake/blob/main/CONTRIBUTING.md#Adding-CHANGELOG-Entry)

### CODE REVIEW

**Comment by mikealfare** [comment]
@kevin868 Thanks for the catch. Unfortunately I did not see this PR until we cut the `1.5.latest` branch. All of the affected changelogs are there now, as well as the built `CHANGELOG.md`. If you'd like, you can pull a branch off of `1.5.latest` and cherry pick your changes into there and resubmit, so that you keep your name on it. I can clean up anything that may happen as part of re-building the changelog.

**Comment by kevin868** [comment]
Thanks @mikealfare I submitted #582
But I don't have permissions to add labels there, for `skip Changelog` :)

**Comment by nssalian** [comment]
Thanks for opening #582. We should close this PR and continue there.

**Comment by kevin868** [comment]
Sounds good - however we are assembling new Changelogs - is that workflow updated to not have this mis-linking behavior to DBT-spark?  @nssalian

**Pull request closed without merging**
