### PR TITLE
fix: add option to use private key for authentication

### LINKED ISSUE #619: [Feature] Allow pem formatted private keys for environment variables.
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt-snowflake functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

This extends the existing feature which allows for der formatted private keys as environment variables.  It would apply the same process to allow the use of either der or pem formatted private keys used as environment variables for authentication with Snowflake.

### Describe alternatives you've considered

The only alternative that comes to mind is that everyone who would otherwise use a pem formatted key would have to convert it to the der format.

### Who will this benefit?

Many people, I hope!  It would certainly be useful to those who, like myself, already have a pem formatted key that is configured for authentication with Snowflake.

### Are you interested in contributing this feature?

Yes!

### Anything else?

https://github.com/dbt-labs/dbt-snowflake/compare/main...gabeschenz:dbt-snowflake:fix/private-keys

### PR DESCRIPTION
**Pull request by jschenz-chwy**
resolves #619 

### Description

This PR adds the option of using a pem private key.

### Checklist

- [X] I have read [the contributing guide](https://github.com/dbt-labs/dbt-snowflake/blob/main/CONTRIBUTING.md) and understand what's expected of me
- [X] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
- [X] I have run this code in development and it appears to resolve the stated issue
- [ ] This PR includes tests
- [ ] I have [opened an issue to add/update docs](https://github.com/dbt-labs/docs.getdbt.com/issues/new/choose)
- [X] I have run `changie new` to [create a changelog entry](https://github.com/dbt-labs/dbt-snowflake/blob/main/CONTRIBUTING.md#Adding-CHANGELOG-Entry)

### CODE REVIEW

**Comment by jschenz-chwy** [comment]
I thought I had already signed the contributor license agreement, but that might have been under my personal account.  I just submitted the form for my work account.

**Comment by jlaneve** [comment]
+1, this would be great to get in! Happy to help however I can

**Comment by patawan** [comment]
Agreed! Would love to get this functionality, also happy to assist wherever I can

**Comment by colin-rogers-dbt** [comment]
As this is not covered with any unit/functional tests has anyone done any manual validation that this will work?

**Comment by jschenz-chwy** [comment]
@colin-rogers-dbt I did run it in my own k8s environment, and it worked as expected.  Not sure if anyone else following this has done something similar, but it would be good to have more than just my experience to share.

**Comment by dbeatty10** [comment]
@jschenz-chwy I just updated the checklist within the PR description:

image

---

We'll definitely need public-facing documentation for PEM vs. DER private keys, could you use the following link to open an issue and describe the content that should go in the docs?
- [opened an issue to add/update docs](https://github.com/dbt-labs/docs.getdbt.com/issues/new?assignees=&labels=content%2Cupcoming+release&projects=&template=new-dbt-feature.yml)

Even better if you're willing to open a PR to update the docs too!

@colin-rogers-dbt or @mikealfare can share what kind of testing they want for this PR.

**Comment by mikealfare** [comment]
> As this is not covered with any unit/functional tests has anyone done any manual validation that this will work?

@colin-rogers-dbt, I don't even see where we're testing the current connection method in our functional tests, do you? I think this is just a miss and manual verification might be sufficient. If we wanted to automate it, we'd need to add a few secrets to the repo before CI would pass.

**Comment by colin-rogers-dbt** [comment]
> > As this is not covered with any unit/functional tests has anyone done any manual validation that this will work?
> 
> @colin-rogers-dbt, I don't even see where we're testing the current connection method in our functional tests, do you? I think this is just a miss and manual verification might be sufficient. If we wanted to automate it, we'd need to add a few secrets to the repo before CI would pass.

@mikealfare Agreed, I'll open an issue to add these tests, in the meantime I'm comfortable moving forward since this has been manually tested

**Review by colin-rogers-dbt — APPROVED** [review]

**Comment by jschenz-chwy** [comment]
I have opened a PR for the doc change here: https://github.com/dbt-labs/docs.getdbt.com/pull/3786

**Comment by colin-rogers-dbt** [comment]
beat me to it, thanks @jschenz-chwy

**Pull request merged**
