### PR TITLE
Safe logic for concurrent executions

### PR DESCRIPTION
**Pull request by rattata2me**
resolves #
[docs](https://github.com/dbt-labs/dbt-snowflake/issues/1123)
### Problem
when running an incremental table with the on_schema_change policy set to append_new_columns in a dbt project. If two jobs concurrently perform the column check operation, they both generate the same ALTER TABLE statement. Because of this simultaneous execution, a race condition occurs where one job's ALTER TABLE statement succeeds, while the slower executor encounters a SQL compilation error stating that the column already exists. This issue stems from the inability to ensure that the column schema remains unchanged between the column check operation and the execution of the ALTER TABLE statement, leading to potential failures in concurrent environments.
### Solution
The solution to this problem is to incorporate the IF NOT EXISTS and IF EXISTS conditions in the ALTER TABLE statements. By using these conditions, the ALTER TABLE statement will only attempt to add a column if it does not already exist, and drop a column only if it exists.
However, this introduces some drawbacks. These include increased complexity in SQL logic, potential masking of underlying schema synchronization issues, minor performance impacts, and the risk of partial schema updates. Additionally, this solution is specific to Snowflake or databases that support these conditions, making it less portable to other database systems.
### Checklist
- [ X] I have read [the contributing guide](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md) and understand what's expected of me
- [ X] I have run this code in development and it appears to resolve the stated issue
- [ X] This PR includes tests, or tests are not required/relevant for this PR
- [ X] This PR has no interface changes (e.g. macros, cli, logs, json artifacts, config files, adapter interface, etc) or this PR has already received feedback and approval from Product or DX

### CODE REVIEW

**Comment by rattata2me** [comment]
This is my proposed solution to resolve the stated concurrency issues stated in https://github.com/dbt-labs/dbt-snowflake/issues/1123 . Right now I can not think of any major drawbacks of fixing the issue by usign the 'IF EXISTS' statements, any feed back on this is appreciated.

**Comment by colin-rogers-dbt** [comment]
By 'concurrent executions' do you mean performing dbt commands like `dbt run`  against the same target in parallel?

**Comment by rattata2me** [comment]
Yes precisely, this happens when executing `dbt run` in two separate processes at the same time against the same target table.

**Comment by amychen1776** [comment]
At this time - we do not intend to support concurrent dbt runs and thus will be closing this PR for now.

**Pull request closed without merging**
