### PR TITLE
enable mfa token cache for linux

### LINKED ISSUE #64: MFA Token not being cached
### Describe the bug
I'm trying to get Snowflake's [DUO-based MFA](https://docs.snowflake.com/en/user-guide/security-mfa.html#connecting-to-snowflake-with-mfa) working when running dbt in a linux container running on my laptop.  Technically it works, but it's not caching the token and I have to repeatedly re-authorize.  I have tried:

* Setting ALLOW_CLIENT_MFA_CACHING to true for the account
* Setting ALLOW_ID_TOKEN to true for the account
* Setting `authenticator: username_password_mfa` in profiles.yml

All that, and yet, every time I run dbt, I get 4 MFA auth requests right away, and then 1 for each model that it runs.  Obviously, this is impractical with 10-100's of models.  I'm wondering what else I might be missing, if anything.  I swear there used to be a note in Snowflake's docs that some aspect of this only worked on Mac and Windows environments, but I can't find that anymore and was hopeful that it had been resolved for linux.  Perhaps this is a dbt defect that isn't sending the right auth method to the python lib?

### System information
**The output of `dbt --version`:**
```
root@bbafbba2e1dc:/dbt-runner/dbt# dbt --version
installed version: 0.21.0
   latest version: 0.21.1

Your version of dbt is out of date! You can find instructions for upgrading here:
https://docs.getdbt.com/docs/installation

Plugins:
  - snowflake: 0.21.0
```

**The operating system you're using:**  Using a linux container built based on [this dockerfile](https://github.com/gnilrets/dbt-container-skeleton/blob/main/Dockerfile) (with some minor modifications)
```
root@bbafbba2e1dc:/dbt-runner/dbt# cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"


root@bbafbba2e1dc:/dbt-runner/dbt# uname -r
5.10.47-linuxkit
```

**The output of `python --version`:**
```
root@bbafbba2e1dc:/dbt-runner/dbt# python --version
Python 3.8.12
```
**Version of snowflake connector:** `snowflake-connector-python[secure-local-storage]==2.5.1`

### PR DESCRIPTION
**Pull request by tekumara**
enables mfa token caching for linux when using the `username_password_mfa` authenticator

resolves #64

### Checklist

- [x] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
- [x] I have run this code in development and it appears to resolve the stated issue
- [x] This PR includes tests, or tests are not required/relevant for this PR
- [ ] I have updated the `CHANGELOG.md` and added information about my change to the "dbt-snowflake next" section.

### CODE REVIEW

**Comment by tekumara** [comment]
@jtcohen6 I think this requires a maintainer to approve before the workflows/checks runs.

**Comment by tekumara** [comment]
@leahwicz would you be able to review this PR? thank you 🙏

**Comment by VersusFacit** [comment]
Hey @tekumara. Sorry for the delay here. I have allocated time today to see this merged if all looks well!

I'm going to approve this PR to get tests running. If everything there looks good, I'll do some more checks, then merge it to test that things look good in dbt Cloud! Please hold for tests to pass

**Comment by emmyoop** [comment]
@cla-bot check

**Review by VersusFacit — APPROVED** [review]
alright, we're looking good. I'm going to merge this and test this in dbt Cloud. I'll ping the issue one time to make sure we wrapped things up. After that, should everything look good, we'll move to backporting this and patch releasing this as needed.

**Pull request merged**
