### PR TITLE
Improve column comment handling when `persist_docs` is enabled

### LINKED ISSUE #73: Use lowercase / case-insensitive comparison when persisting column-level comments for views
See https://github.com/dbt-labs/dbt-snowflake/issues/72 for context

https://github.com/dbt-labs/dbt-snowflake/blob/e75986f0b81749bc790f52dcea4ecd1c1a7f3f2a/dbt/include/snowflake/macros/adapters.sql#L47-L50

This check should use `|lower` instead of `|upper`, since Snowflake columns are almost always uppercase.

```python
model_columns:  {'id': {'name': 'id', 'description': 'this is a cool column', 'meta': {}, 'tags': []}}
query_columns:  ['ID']
```

That will enable users to persist descriptions for columns defined in lowercase:
```yml
version: 2

models:
  - name: my_cool_view_model
    description: this is a cool model
    config:
      materialized: view
      persist_docs:
        relation: true
        columns: true
    columns:
      - name: id # instead of ID
        description: this is a cool column
```

### LINKED ISSUE #100: [CT-315] CREATE VIEW statement column list includes invalid CAST()
### Describe the bug
A clear and concise description of what the bug is. What command did you run? What happened?
Models that include a cast of a column only in the final CTE results in the CREATE VIEW statement performing the cast in the view column list. This applies to both hard-coded string literals and columns selected from another object.

### Steps To Reproduce
In as much detail as possible, please provide steps to reproduce the issue. Sample data that triggers the issue, example model code, etc is all very helpful here.

Model code:
```
--test_model.sql
with test_unioned as (
        select '1' as column1
        union
        select '2' as column1
    )
    
    , final as (
        select cast(column1 as varchar)
        from test_unioned
    )
    
    select * from final
)
```

Resulting `dbt run` sql:
```
create
or replace view MY_DB.PUBLIC.test_model (
    CAST(COLUMN1 AS VARCHAR)
) as (
    with test_unioned as (
        select
            '1' as column1
        union
        select
            '2' as column1
    ),
    final as (
        select
            cast(column1 as varchar)
        from
            test_unioned
    )
    select
        *
    from
        final
);
```

To work around the issue, change model to cast columns before the final CTE as below:
```
with test_unioned as (
        select cast('1' as varchar) as column1
        union
        select cast('2' as varchar) as column1
    )
    
    , final as (
        select column1
        from test_unioned
    )
    
    select * from final
```

### Expected behavior
For Snowflake, CAST() in the column list of a CREATE VIEW statement is not valid syntax. dbt run should not build CREATE VIEW statements that include this function in the column list.

### Screenshots and log output
If applicable, add screenshots or log output to help explain your problem.

### System information
**The output of `dbt --version`:**
```
dbt --version
installed version: 1.0.3
   latest version: 1.0.3

Up to date!

Plugins:
  - snowflake: 1.0.0 - Up to date!
```

**The operating system you're using:**
Windows 10

**The output of `python --version`:**
Python 3.9.10

### Additional context
It would appear that computed columns with simple expressions are supported by Snowflake, but CAST() isn't included in this list of functions. (ref: https://community.snowflake.com/s/question/0D50Z00008ixGQKSA2/does-snowflake-supports-computed-columns-in-a-table-while-creating-table)

### PR DESCRIPTION
**Pull request by LewisDavies**
resolves #73, resolves #100 

### Description
This PR improves how column comments are handled when `persist_docs` is enabled. 
- Column names defined in models are now matched to docs regardless of casing
- All comment definitions are quoted in a way that preserves the original intent. 
- Reserved keywords can now be used as column names (this was my initial problem - I have a ton of mostly identical tables from MongoDB with column names like `order` 🤦 )

Example model:
```sql
-- view_model.sql
select
  -- Can be queried 
  1 as col_lower,
  2 as "Col_Mixed",
  3 as order,
  cast(4 as text)
```

Docs:
``` yml
models:
  - name: view_model
    columns:
      - name: col_lower
        description: Lower description
      - name: Col_Mixed
        description: Mixed description
      - name: order
        description: Order description
```

Compiled table definition
```sql
create or replace table <db>.<schema>.test_model 
(
  "COL_LOWER" $$Lower description$$,
  "Col_Mixed" $$Mixed description$$,
  "ORDER" as $$Order description$$,
  "CAST(4 AS TEXT)" $$$$
)
as ...
```

Example query
```sql
select
  col_lower,  -- Could also be COL_LOWER or "COL_LOWER"
  "Col_Mixed",
  "ORDER",  -- Quotes added for reserved keyword
  "CAST(4 AS TEXT)"
from 
  view_model
```

Tests have been added for examples like these. I also removed some redundant tests designed for BigQuery.

### Caveats
For the example `cast(4 as text)` from #100, the behaviour is now inconsistent between tables and views. A view will create the column using quotes & uppercase, but a table will fail with an error. This is because the table creation macro doesn't use `get_column_comment_sql`.

### Checklist

- [x] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
- [x] I have run this code in development and it appears to resolve the stated issue
- [x] This PR includes tests, or tests are not required/relevant for this PR
- [x] I have updated the `CHANGELOG.md` and added information about my change to the "dbt-snowflake next" section.

### CODE REVIEW

**Comment by jkjetty** [comment]
This looks like it almost solves #102 but doesn't check for comments before inserting the full statement. I will wait and try to implement a fix for #102 on top of this once it ships.

**Comment by McKnight-42** [comment]
cla-bot check

**Comment by McKnight-42** [comment]
clabot check

**Comment by McKnight-42** [comment]
Clabot check

**Comment by McKnight-42** [comment]
@LewisDavies This is looking great, just wanted to double check if you've signed our cla agreement as our verification isn't going through.

**Comment by LewisDavies** [comment]
@McKnight-42 Thanks for pointing that out, I thought I'd already signed. Just submitted the form and updated the changelog so hopefully we're good to go now

**Review by jtcohen6 — APPROVED** [review]
Thanks so much for the contribution @LewisDavies! A number of people have run into these issues, and I'm hopeful that we'll see far fewer folks running into them in the future.

**Pull request merged**
