### PR TITLE
ADAP-1115: Move to `hatch` and `pyproject.toml`

### PR DESCRIPTION
**Pull request by mikealfare**
We are moving to a monorepo that uses `pyproject.toml` and `hatch`. This requires a series of migrations, including this one. This PR inclues:

- update from `setup.py`/`dev-requirements.txt` to `pyproject.toml`/`hatch.toml`
- move tool config (e.g. `mypy` and `pytest`) into `pyproject.toml`
- update workflows regarding these moves
- delete configs that no longer apply (e.g. `tox.ini`, `pytest.ini`, etc.)

### CODE REVIEW

**Comment by mikealfare** [comment]
Since CI is target branch based, here's the actual integration test run: https://github.com/dbt-labs/dbt-snowflake/actions/runs/11883218656

**Comment by mikealfare** [comment]
Integrations that run against the workflow in this branch:
https://github.com/dbt-labs/dbt-snowflake/actions/runs/12215746378

**Comment by mikealfare** [comment]
Integration tests running against the workflow in this branch:
https://github.com/dbt-labs/dbt-snowflake/actions/runs/12216096614

**Comment by mikealfare** [comment]
Integration tests running against the workflow in this branch, now using a hard pinned ubuntu image:

https://github.com/dbt-labs/dbt-snowflake/actions/runs/12241551824

Previous runs were passing on macos and windows, but not ubuntu. GH is currently migrating ubuntu-latest from 22.04 to 24.04, os this might be impacting the runs here.

**Comment by mikealfare** [comment]
Working integration tests: https://github.com/dbt-labs/dbt-snowflake/actions/runs/12422067422

**Review by VersusFacit — APPROVED** [review]

**Pull request merged**
