### PR TITLE
remove graph_selection test

### PR DESCRIPTION
**Pull request by McKnight-42**
resolves #

### Description

remove duplicated test
### Checklist

- [x] I have read [the contributing guide](https://github.com/dbt-labs/dbt-snowflake/blob/main/CONTRIBUTING.md) and understand what's expected of me
- [x] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
- [ ] I have run this code in development and it appears to resolve the stated issue
- [ ] This PR includes tests, or tests are not required/relevant for this PR
- [ ] I have [opened an issue to add/update docs](https://github.com/dbt-labs/docs.getdbt.com/issues/new/choose), or docs changes are not required/relevant for this PR
- [ ] I have run `changie new` to [create a changelog entry](https://github.com/dbt-labs/dbt-snowflake/blob/main/CONTRIBUTING.md#Adding-CHANGELOG-Entry)

### CODE REVIEW

**Comment by McKnight-42** [comment]
There is a core version of this tests https://github.com/dbt-labs/dbt-core/blob/main/tests/functional/graph_selection/test_graph_selection.py up all setup in general is the same but some of the running methods would be different between the two because of differences in how model names are represented, would we still like to pull in the `SelectionFixtures` for this and move test in core to adapter zone or is that not worth it since core also has some other tests in that section

**Comment by VersusFacit** [comment]
It's only worth it if the adapter zone test would be used in this test. But, I don't think that's possible because Snowflake uses it's own settings right? If I misheard you earlier, then yes, we should move the core to the adapter zone and reimport some of those test classes here.

**Comment by McKnight-42** [comment]
after quick discussion with jeremey on the core move pr just going to remove the tests as this may not be adapter specific in anyway

**Review by VersusFacit — APPROVED** [review]
I love trimming unneeded code. Thanks for looking into this.

**Review by nssalian — APPROVED** [review]
Thanks for checking with core to make sure this is good.

**Pull request merged**
