### PR TITLE
Adds `query_tag` to the tuple returned by _connection_keys()

### LINKED ISSUE #251: [CT-1133] [Bug] Not all jinja target attributes are available from profiles.yml
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

I am currently trying to access `target.query_tag` based on the currently set value in my `profiles.yml` but it does not appear in the target object when I log it out during parsing.

profiles.yml
```yaml
config:
    send_anonymous_usage_stats: False
    use_colors: True

integration_tests:
  outputs:

    bigquery:
      type: bigquery
      method: service-account
      keyfile: "{{ env_var('BIGQUERY_SERVICE_KEY_PATH') }}"
      project: "{{ env_var('BIGQUERY_TEST_DATABASE') }}"
      schema: "{{ env_var('TEST_SCHEMA') }}"
      location: us
      threads: 4

    snowflake:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT_ID') }}"
      user: "{{ env_var('SNOWFLAKE_USERNAME') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: "{{ env_var('SNOWFLAKE_ROLE') }}"
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE') }}"
      database: "{{ env_var('SNOWFLAKE_TEST_DATABASE') }}"
      schema: "{{ env_var('TEST_SCHEMA') }}"
      threads: 4
      client_session_keep_alive: False
      query_tag: dbt_integration_tests
      connect_retries: 0
      connect_timeout: 10
      retry_on_database_errors: False
      retry_all: False
```

log output of `target` object from dbt parse -t snowflake
```
{
    'account': 'XXXXXX',
    'user': 'XXXXXX',
    'database': 'XXXXXX',
    'schema': 'XXXXXX',
    'warehouse': 'XXXXXX',
    'role': 'ACCOUNTADMIN',
    'client_session_keep_alive': False,
    'type': 'snowflake',
    'threads': 4,
    'name': 'snowflake',
    'target_name': 'snowflake',
    'profile_name': 'integration_tests',
    'config': {
        'send_anonymous_usage_stats': False,
        'use_colors': True
    }
}
```

### Expected Behavior

I would expect the target object to contain all properties defined in profiles.yml

### Steps To Reproduce

Using snowflake target and profiles.yml with query_tag defined, try to access `target.query_tag`

### Relevant log output

_No response_

### Environment

```markdown
- OS:macOS 12.3
- Python: 3.8.11
- dbt: 1.2.1
- dbt-snowflake: 1.2.0
```

### Which database adapter are you using with dbt?

snowflake

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by Surbias**
resolves #251 

### Description

According to [here](https://github.com/dbt-labs/dbt-snowflake/issues/251#issuecomment-1239173629)
> The simple fix, in this case, is to add query_tag to the tuple returned by SnowflakeCredentials._connection_keys().

### Checklist

- [x] I have read [the contributing guide](https://github.com/dbt-labs/dbt-snowflake/blob/main/CONTRIBUTING.md) and understand what's expected of me
- [x] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
- [x] I have run this code in development and it appears to resolve the stated issue
- [x] This PR includes tests, or tests are not required/relevant for this PR
- [x] I have [opened an issue to add/update docs](https://github.com/dbt-labs/docs.getdbt.com/issues/new/choose), or docs changes are not required/relevant for this PR
- [x] I have run `changie new` to [create a changelog entry](https://github.com/dbt-labs/dbt-snowflake/blob/main/CONTRIBUTING.md#Adding-CHANGELOG-Entry)

### CODE REVIEW

**Review by ChenyuLInx — APPROVED** [review]
@Surbias Thanks for making this change! Looks good to me!
[Here's](https://github.com/dbt-labs/dbt-snowflake/blob/31e389064bf600ac42f17940ff0f94c1e39abf40/tests/unit/test_snowflake_adapter.py#L267) a test that tests similar piece `client_session_keep_alive`, are you comfortable adding one for `query_tag` similar to it?

**Comment by Surbias** [comment]
@ChenyuLInx sure I'll give it a try!

**Comment by Surbias** [comment]
@ChenyuLInx added the unit test `test_client_has_query_tag`.

This unit tests asserts both the client and credentials logic for query_tag. 
    
On the credentials opted to assert against `.connection_info` over `_connection_keys` as to not use a function intended to be private.

Please let me know if this makes sense and if there are any improvements I can make! 😄

**Comment by ChenyuLInx** [comment]
@Surbias Sorry for the slow response! The changes looks good. The only thing that's failing now is code-quality check, I tested that the `main` branch also has this issue. @colin-rogers-dbt do we want to just add `  # type: ignore` to that line? or is there something else you would like to do about it?

**Comment by McKnight-42** [comment]
@ChenyuLInx I do believe the `ignore` is the correct fix and may of already been done actually going to update the branch with main to double check.

**Review by colin-rogers-dbt — CHANGES_REQUESTED** [review]
need to update unit test cases

**Comment by McKnight-42** [comment]
@Surbias thank you for all your hard work on this, going to close out this pr in favor of #517 so we can get your change in

**Pull request closed without merging**
