### PR TITLE
Change how a column of type VECTOR is parsed

### LINKED ISSUE #1098: [Bug] Support Vector data types for macro `snowflake__get_columns_in_relation`
### Is this a new bug in dbt-snowflake?

- [X] I believe this is a new bug in dbt-snowflake
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

When trying to run an incremental load referencing a table that has a column that is cast as a VECTOR data type, I get the following error: `Could not interpret data_type "VECTOR(FLOAT, 1536)": could not convert "FLOAT" to an integer`

This appears to be due to the `from_description` Column function [here](https://github.com/dbt-labs/dbt-adapters/blob/main/dbt/adapters/base/column.py#L130) expecting only integers within parenthesis.

### Expected Behavior

Expected column data type to be properly parsed and reproduced in the incremental table.

### Steps To Reproduce

do `dbt run` on a model that has an incremental load materialization and has a column that is the VECTOR data type

### Relevant log output

```shell
15:40:11  Snowflake adapter: Error running SQL: macro get_columns_in_relation
15:40:11  Snowflake adapter: Rolling back transaction.
15:40:11  On <model name>: Close
15:40:11  Runtime Error in model <model name> (<model name>.sql)
  Could not interpret data_type "VECTOR(FLOAT, 1536)": could not convert "FLOAT" to an integer
```

### Environment

```markdown
- OS: Ubuntu 22.04.4 LTS
- Python:  3.11.7
- dbt-core: 1.8.3
- dbt-snowflake: 1.8.3
```

### Additional Context

suspected cause of the issue: 
https://github.com/dbt-labs/dbt-snowflake/blob/2576a08379e248d393b9a698e58fac0d32c23648/dbt/include/snowflake/macros/adapters.sql
https://github.com/dbt-labs/dbt-adapters/blob/main/dbt/adapters/base/column.py#L130

### PR DESCRIPTION
**Pull request by achawkins**
resolves #1098
[docs](https://github.com/dbt-labs/docs.getdbt.com/issues/new/choose) dbt-labs/docs.getdbt.com/#

### Problem

When an incremental (maybe other materializations, but I have not checked) model with a `VECTOR` type is run, it will fail to create the `SnowflakeColumn` object from the `from_description` class method. This is because the [`dbt-adapters` `Column.from_description`](https://github.com/dbt-labs/dbt-adapters/blob/main/dbt/adapters/base/column.py#L127) method does some parsing to extract the precision and scale of a numeric type and tries to cast both values within parenthesis to integers. The Snowflake vector is of the form `VECTOR(<data_type>, <dimension>)`, so the `<data_type>` will fail to be cast as an integer.

### Solution

If the data type has the word `VECTOR` in it, bypass the additional parsing done in `dbt-adapters` and return a `SnowflakeColumn` that uses the raw data type as the parsed data type. If it does not, then pass it through to the default `from_description` method.

### Checklist

- [X] I have read [the contributing guide](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md) and understand what's expected of me
- [X] I have run this code in development and it appears to resolve the stated issue
- [X] This PR includes tests, or tests are not required/relevant for this PR
- [X] This PR has no interface changes (e.g. macros, cli, logs, json artifacts, config files, adapter interface, etc) or this PR has already received feedback and approval from Product or DX

### CODE REVIEW

**Comment by colin-rogers-dbt** [comment]
@achawkins this looks pretty merge-able, are you able to sign our CLA and add a changelog?

**Comment by achawkins** [comment]
@colin-rogers-dbt I must have signed the CLA with a different email before. I resigned it and added the changelog entry.

**Comment by colin-rogers-dbt** [comment]
@cla-bot check

**Comment by liorchen** [comment]
can this be merged? blocking us from moving forward

**Comment by ChenVilinsky** [comment]
Is there any update on this PR status?
It's a real blocker...

**Comment by colin-rogers-dbt** [comment]
@cla-bot check

**Review by colin-rogers-dbt — APPROVED** [review]

**Comment by colin-rogers-dbt** [comment]
Looks like the git commits aren't signed correctly but manually confirmed the CLA has been signed

**Comment by dassowmd** [comment]
Any idea when this change will be released? I confirmed if fixes my issue on https://github.com/dbt-labs/dbt-snowflake/issues/1098

**Pull request merged**
